apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql-pod
  name: mysql-pod
spec:
  containers:
  -	image: mysql
    name: mysql-pod
  envFrom:
  - configMapRef:
     name: db-config
  - secretRef:
     name: db-secret
resources:
